base_model: "Qwen/Qwen2.5-3B-Instruct"  
adapter: "../models/model_correctness_1epoch"

dataset: "../dataset/model_correctness_prompt/test"
prompt_column: "prompt"

output_dir: "../inference/output/new_result/model_correctness_1epoch"

batch_size: 4
max_new_tokens: 4096
limit: 1
temperature: 0.0
top_p: 1.0
do_sample: false
trust_remote_code: false
